### ISSUE TITLE
Should I make a PR to update documentation / deployment?

### ISSUE THREAD

**Issue by yingw787** [aclark4life/dcpython#1]
Hey @aclark4life,

I'm not terribly familiar with Makefiles, and one common denominator I've had with other software engineers in other divisions is an understanding of bash or sh. Should I go ahead and make a PR to add instructions in the README?

Also, I've found great success in an extremely cheap Dockerization setup (three files, maybe 20 lines total) that abstracts away pretty much all dependencies: https://bytes.yingw787.com/posts/2020/02/27/docker_as_vagrant/

I think Docker runs fine on macOS and Linux, but there may be problems with BSD and Windows. I don't think Windows Home has hypervisors installed, and WSL 1.x maps native Windows APIs unlike WSL 2.x which has a Linux kernel.

If you think it's worth it, I can add Dockerization too.

**Comment by aclark4life** [comment]
@yingw787 This is actually a static site running on AWS S3, so for now let's just do PRs for content fixes (if you have any)… otherwise, thanks!

**Comment by yingw787** [comment]
Sounds good, I'll go ahead and close this issue.
